In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [59]:
df = pd.read_csv('cardekho_imputated.csv')
df.head(10)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
5,5,Maruti Wagon R,Maruti,Wagon R,8,35000,Individual,Petrol,Manual,18.90,998,67.10,5,350000
6,6,Hyundai i10,Hyundai,i10,8,40000,Dealer,Petrol,Manual,20.36,1197,78.90,5,315000
7,7,Maruti Wagon R,Maruti,Wagon R,3,17512,Dealer,Petrol,Manual,20.51,998,67.04,5,410000
8,8,Hyundai Venue,Hyundai,Venue,2,20000,Individual,Petrol,Automatic,18.15,998,118.35,5,1050000
9,12,Maruti Swift,Maruti,Swift,4,28321,Dealer,Petrol,Manual,16.60,1197,85.00,5,511000

In [60]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [61]:
df.car_name.value_counts()

car_name
Hyundai i20           906
Maruti Swift Dzire    890
Maruti Swift          781
Maruti Alto           778
Honda City            757
                     ...
Mercedes-AMG C          1
Tata Altroz             1
Ferrari GTC4Lusso       1
Hyundai Aura            1
Force Gurkha            1
Name: count, Length: 121, dtype: int64

In [62]:
df.car_name.unique()

array(['Maruti Alto', 'Hyundai Grand', 'Hyundai i20', 'Ford Ecosport',
       'Maruti Wagon R', 'Hyundai i10', 'Hyundai Venue', 'Maruti Swift',
       'Hyundai Verna', 'Renault Duster', 'Mini Cooper', 'Maruti Ciaz',
       'Mercedes-Benz C-Class', 'Toyota Innova', 'Maruti Baleno',
       'Maruti Swift Dzire', 'Volkswagen Vento', 'Hyundai Creta',
       'Honda City', 'Mahindra Bolero', 'Toyota Fortuner', 'Renault KWID',
       'Honda Amaze', 'Hyundai Santro', 'Mahindra XUV500',
       'Mahindra KUV100', 'Maruti Ignis', 'Datsun RediGO',
       'Mahindra Scorpio', 'Mahindra Marazzo', 'Ford Aspire', 'Ford Figo',
       'Maruti Vitara', 'Tata Tiago', 'Volkswagen Polo', 'Kia Seltos',
       'Maruti Celerio', 'Datsun GO', 'BMW 5', 'Honda CR-V',
       'Ford Endeavour', 'Mahindra KUV', 'Honda Jazz', 'BMW 3', 'Audi A4',
       'Tata Tigor', 'Maruti Ertiga', 'Tata Safari', 'Mahindra Thar',
       'Tata Hexa', 'Land Rover Rover', 'Maruti Eeco', 'Audi A6',
       'Mercedes-Benz E-Class', 'Audi Q7', 'BMW Z4', 'BMW 6', 'Jaguar XF',
       'BMW X5', 'MG Hector', 'Honda Civic', 'Isuzu D-Max',
       'Porsche Cayenne', 'BMW X1', 'Skoda Rapid', 'Ford Freestyle',
       'Skoda Superb', 'Tata Nexon', 'Mahindra XUV300',
       'Maruti Dzire VXI', 'Volvo S90', 'Honda WR-V', 'Maruti XL6',
       'Renault Triber', 'Lexus ES', 'Jeep Wrangler', 'Toyota Camry',
       'Hyundai Elantra', 'Toyota Yaris', 'Mercedes-Benz GL-Class',
       'BMW 7', 'Maruti S-Presso', 'Maruti Dzire LXI', 'Hyundai Aura',
       'Volvo XC', 'Maserati Ghibli', 'Bentley Continental', 'Honda CR',
       'Nissan Kicks', 'Mercedes-Benz S-Class', 'Hyundai Tucson',
       'Tata Harrier', 'BMW X3', 'Skoda Octavia', 'Jeep Compass',
       'Mercedes-Benz CLS', 'Datsun redi-GO', 'Toyota Glanza',
       'Porsche Macan', 'BMW X4', 'Maruti Dzire ZXI', 'Volvo XC90',
       'Jaguar F-PACE', 'Audi A8', 'ISUZU MUX', 'Ferrari GTC4Lusso',
       'Mercedes-Benz GLS', 'Nissan X-Trail', 'Jaguar XE', 'Volvo XC60',
       'Porsche Panamera', 'Mahindra Alturas', 'Tata Altroz', 'Lexus NX',
       'Kia Carnival', 'Mercedes-AMG C', 'Lexus RX', 'Rolls-Royce Ghost',
       'Maserati Quattroporte', 'Isuzu MUX', 'Force Gurkha'], dtype=object)

In [63]:
df.model.unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [64]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='object')

In [65]:
df.drop(columns=['car_name','brand'],inplace=True)

In [66]:
df.head(3)

,Unnamed: 0,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Alto,9,120000,Individual,Petrol,Manual,19.7,796,46.3,5,120000
1,1,Grand,5,20000,Individual,Petrol,Manual,18.9,1197,82.0,5,550000
2,2,i20,11,60000,Individual,Petrol,Manual,17.0,1197,80.0,5,215000

In [67]:
df.columns

Index(['Unnamed: 0', 'model', 'vehicle_age', 'km_driven', 'seller_type',
       'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power',
       'seats', 'selling_price'],
      dtype='object')

In [68]:
X = df.drop(columns=['Unnamed: 0','selling_price'])
y= df['selling_price']

In [69]:
X.head(5)

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [70]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
15406     250000
15407     925000
15408     425000
15409    1225000
15410    1200000
Name: selling_price, Length: 15411, dtype: int64

In [71]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [72]:
df['model'].dtype

dtype('O')

In [73]:
df.drop('Unnamed: 0', inplace = True,axis=1)

In [74]:
df.columns

Index(['model', 'vehicle_age', 'km_driven', 'seller_type', 'fuel_type',
       'transmission_type', 'mileage', 'engine', 'max_power', 'seats',
       'selling_price'],
      dtype='object')

In [75]:
num_feature = [feature for feature in X.columns if X[feature].dtype !='O']
print(num_feature)

['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']

In [76]:
cat_features = [feature for feature in X.columns if X[feature].dtype =='O']
print(cat_features)

['model', 'seller_type', 'fuel_type', 'transmission_type']

In [77]:
des_features = [feature for feature in num_feature if len(X[feature].unique())<=25]
print(des_features)

['vehicle_age', 'seats']

In [78]:
con_feature = [feature for feature in num_feature if feature not in des_features]
print(con_feature)

['km_driven', 'mileage', 'engine', 'max_power']

In [79]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

labelencoder = LabelEncoder()

X_train['model'] = labelencoder.fit_transform(X_train['model'])
X_test['model'] = labelencoder.transform(X_test['model'])

In [80]:
X_train.head(5)

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
8838,114,5,70000,Individual,Diesel,Automatic,16.00,2179,140.00,7
718,89,12,94000,Dealer,Diesel,Manual,19.30,1248,73.90,5
9477,77,4,48000,Dealer,Petrol,Manual,15.00,1598,103.52,5
3166,117,8,38100,Dealer,Petrol,Manual,20.36,1197,78.90,5
666,13,5,33000,Dealer,Diesel,Manual,27.39,1248,74.00,5

In [81]:
from sklearn.compose import ColumnTransformer

column_trans = ColumnTransformer([
    ('Classification',OneHotEncoder(drop='first'),cat_features),
    ('Numerical',StandardScaler(),con_feature)
],remainder='passthrough')

In [82]:
X_train = column_trans.fit_transform(X_train)
X_test = column_trans.transform(X_test)

In [83]:
X_train

<12328x132 sparse matrix of type '<class 'numpy.float64'>'
	with 112785 stored elements in Compressed Sparse Row format>

In [84]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train,y_train)

RandomForestRegressor()

In [85]:
from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_test)

print(mean_squared_error(y_test,y_pred))

38389909190.0552

In [86]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [92]:
def eval_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    r2_score_2 = r2_score(true,predicted)
    return mae,mse,r2_score_2

In [94]:
models = {
    "Linear Regression" : LinearRegression(),
    "Ridge" : Ridge(),
    "Lasso" : Lasso(),
    "K-Neighbors Regressor" : KNeighborsRegressor(),
    "Decision Tree Regressor" : DecisionTreeRegressor(),
    "Random Forest Regressor" : RandomForestRegressor()
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_pred = model.predict(X_test)
    print(f'{i} = ',eval_model(y_test,y_pred))

0 =  (171013.85872477383, 123794866948.51524, 0.7830103948592465)
1 =  (186898.51228866374, 134597286084.04367, 0.764075743362282)
2 =  (170999.1962995729, 123780467481.10413, 0.7830356344739802)
3 =  (98218.74797275382, 46249068699.31885, 0.9189338992595998)
4 =  (119106.28176019028, 62672407428.91124, 0.8901468107972874)
5 =  (93393.31905566953, 37030036861.97756, 0.9350931644009943)

In [95]:
knn_params = {"n_neighbours":[2,3,10,20,40,50]}
rf_params = {"max_depth":[5,8,15,None,10],
             "max_features":[5,7,"auto",8],
             "min_samples_split":[2,8,15,20],
             "n_estimators":[100,200,500,1000]}

In [96]:
randomcv_models = [('KNN',KNeighborsRegressor(),knn_params),
                   ("RF",RandomForestRegressor(),rf_params)]

In [97]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
model_param = {}
for name , model, param in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                )